#!/bin/bash
for artis in *
do 
	cd $artist
	for album in *
	do
		if [[ -d "$album" ]]
		then
			cd $album
			for song in *.mp3;
			do
		       		ffmpeg -i $name -filter:a loudnorm $name
			done
			cd ..
		fi
	done
done
			
