#! /bin/bash

files=(~/Pictures/Wallpapers/*)

if [ -z "$1" ]
then
	path=${files[RANDOM % ${#files[@]}]}
else
	path=$1
fi

feh --bg-fill $path
wpg -s $path
wal -n -i $path
betterlockscreen -u $path
alacritty_colors.sh
